baseurl: '/'
permalink: pretty
title: 'Atriva Inc.'

logo:
  mobile: "images/logo/logo.png" # "logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/AtrivaTextOnly.svg" # "images/logo/logo.svg"
  desktop_height: "120px" # "30px"
  desktop_width: "240px" # "120px"

home: 
  limit_resources: 6

collections:
  resources:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

